version: '3'
services:
  transfer-api:
    container_name: transfer-api
    image: transfer-api
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - PORT=3000
      - URL_DATABASE=mongodb://transfer-api-db:27017/transfer

  transfer-api-db:
      container_name: transfer-api-db
      image: mongo
      volumes:
        - transfer-api-db:/data/db
      ports:
        - "27011:27017"

volumes:
  transfer-api-db: